name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libdav1d-dev nasm
        # Create symlink for zig linker to find dav1d
        ln -s /lib/x86_64-linux-gnu/libdav1d.so $HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libdav1d.so

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install dav1d nasm
        # Create directories and symlinks for zig linker to find dav1d on macOS
        mkdir -p /Users/runner/Library/Caches/cargo-zigbuild/0.20.0/deps/
        # Find the actual homebrew dav1d library and create symlinks
        DAV1D_LIB=$(find /opt/homebrew/lib /usr/local/lib -name "libdav1d.dylib" 2>/dev/null | head -1)
        if [ -n "$DAV1D_LIB" ]; then
          ln -sf "$DAV1D_LIB" /Users/runner/Library/Caches/cargo-zigbuild/0.20.0/deps/libdav1d.dylib
        fi


    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
      
    - name: Install dependencies (Unix)
      if: runner.os != 'Windows'
      run: |
        source .venv/bin/activate
        uv pip install maturin[dev] numpy pillow
        

    - name: Build and test (Unix)
      if: runner.os != 'Windows'
      run: |
        source .venv/bin/activate
        maturin develop
        python -c "import images; print('Import successful')"
        
        
    - name: Run comprehensive tests (Unix)
      if: runner.os != 'Windows'
      run: |
        source .venv/bin/activate
        python test_basic.py
        
